spring:
  datasource:
    dbadmin:
      dataSourceClassName: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://localhost:3306/db_multidb_admin
      username: root
      password: root
    dbuser:
      dataSourceClassName: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://localhost:3306/db_multidb_user
      username: root
      password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9091